name = "Catppuccin Macchiato yellow"

[colors]
bg_base         = "#24273a"
bg_active       = "#6e738d"
primary         = "#a6da95"
secondary       = "#363a4f"
accent          = "#eed49f"
warning         = "#f5a97f"
danger          = "#ed8796"
fg_primary      = "#24273a"
fg_secondary    = "#cad3f5"
fg_muted        = "#a5adcb"
border_focus    = "#c6a0f6"
