name = "Catppuccin Frapp√©"

[colors]
bg_base         = "#303446"
bg_active       = "#737994"
primary         = "#a6d189"
secondary       = "#414559"
accent          = "#e78284"
warning         = "#ef9f76"
danger          = "#e78284"
fg_primary      = "#303446"
fg_secondary    = "#c6d0f5"
fg_muted        = "#a5adce"
border_focus    = "#ca9ee6"
